services:
  node:
    image: "node:16"
    user: "node"
    working_dir: /var/www/html/node_app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/var/www/html/node_app
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
    command: "yarn dev"